/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlachatRouteImport } from './routes/alachat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesAiProductPhotographyRouteImport } from './routes/guides.ai-product-photography'
import { Route as ApiEnhancePostRouteImport } from './routes/api.enhance-post'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlachatRoute = AlachatRouteImport.update({
  id: '/alachat',
  path: '/alachat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAiProductPhotographyRoute =
  GuidesAiProductPhotographyRouteImport.update({
    id: '/guides/ai-product-photography',
    path: '/guides/ai-product-photography',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEnhancePostRoute = ApiEnhancePostRouteImport.update({
  id: '/api/enhance-post',
  path: '/api/enhance-post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alachat': typeof AlachatRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/work': typeof WorkRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/guides/ai-product-photography': typeof GuidesAiProductPhotographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alachat': typeof AlachatRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/work': typeof WorkRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/guides/ai-product-photography': typeof GuidesAiProductPhotographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alachat': typeof AlachatRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/login': typeof LoginRoute
  '/work': typeof WorkRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/guides/ai-product-photography': typeof GuidesAiProductPhotographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alachat'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/work'
    | '/api/enhance-post'
    | '/guides/ai-product-photography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alachat'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/work'
    | '/api/enhance-post'
    | '/guides/ai-product-photography'
  id:
    | '__root__'
    | '/'
    | '/alachat'
    | '/dashboard'
    | '/editor'
    | '/login'
    | '/work'
    | '/api/enhance-post'
    | '/guides/ai-product-photography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlachatRoute: typeof AlachatRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  LoginRoute: typeof LoginRoute
  WorkRoute: typeof WorkRoute
  ApiEnhancePostRoute: typeof ApiEnhancePostRoute
  GuidesAiProductPhotographyRoute: typeof GuidesAiProductPhotographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alachat': {
      id: '/alachat'
      path: '/alachat'
      fullPath: '/alachat'
      preLoaderRoute: typeof AlachatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/ai-product-photography': {
      id: '/guides/ai-product-photography'
      path: '/guides/ai-product-photography'
      fullPath: '/guides/ai-product-photography'
      preLoaderRoute: typeof GuidesAiProductPhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-post': {
      id: '/api/enhance-post'
      path: '/api/enhance-post'
      fullPath: '/api/enhance-post'
      preLoaderRoute: typeof ApiEnhancePostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlachatRoute: AlachatRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  LoginRoute: LoginRoute,
  WorkRoute: WorkRoute,
  ApiEnhancePostRoute: ApiEnhancePostRoute,
  GuidesAiProductPhotographyRoute: GuidesAiProductPhotographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
